[build]
  command = "astro build"
  publish = "dist"

[context.production.environment]
  PUBLIC_VOTE_API_URL = "https://api.jeromeabel.net/vote.php"

[context.deploy-preview.environment]
  PUBLIC_VOTE_API_URL = "https://api.jeromeabel.net/vote-staging.php"
